# Generated by Django 3.1.1 on 2020-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_bids_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='startingPrice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='user',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
