# Generated by Django 3.1.1 on 2020-09-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200908_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='startingPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
