# Generated by Django 3.1.1 on 2020-09-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200908_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='user',
        ),
    ]
