# Generated by Django 3.1.1 on 2020-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctionlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
