# Generated by Django 3.1.1 on 2020-09-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='catagory',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home')], default='1', max_length=100),
        ),
    ]
