# Generated by Django 3.1.1 on 2020-09-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200909_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image',
            field=models.ImageField(default=1, upload_to='pic_folder/'),
            preserve_default=False,
        ),
    ]
