# Generated by Django 3.1.1 on 2020-09-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200909_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='image',
            field=models.ImageField(default='media/no image', upload_to='media/'),
        ),
    ]
