# Generated by Django 3.1.1 on 2020-09-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200911_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='newItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('startingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('description', models.CharField(default='Enter description here.', max_length=100)),
                ('catagory', models.CharField(choices=[('other', 'Other'), ('fashion', 'Fashion'), ('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home')], default='Other', max_length=100)),
            ],
        ),
    ]
