# Generated by Django 3.1.1 on 2020-09-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200915_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auction',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auctionid',
            field=models.ManyToManyField(blank=True, related_name='key', to='auctions.auctionList'),
        ),
    ]
