# Generated by Django 3.1.1 on 2020-09-17 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200915_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auctionid',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='auctionid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='auctions.watchlist'),
        ),
    ]
