# Generated by Django 3.1.1 on 2020-09-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200917_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='auctionid',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auctionid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key', to='auctions.auctionlist'),
        ),
    ]
