# Generated by Django 3.1.1 on 2020-09-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20200917_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auctionid',
            new_name='auction',
        ),
    ]
