# Generated by Django 3.1.1 on 2020-09-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20200917_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='currentBid',
        ),
        migrations.AddField(
            model_name='bids',
            name='auction_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.auctionlist'),
        ),
        migrations.AddField(
            model_name='bids',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
