# Generated by Django 3.1.1 on 2020-09-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_bids_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='auction_item',
            field=models.IntegerField(null=True),
        ),
    ]
