# Generated by Django 3.1.1 on 2020-09-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auctionlist_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
    ]
