# Generated by Django 3.1.1 on 2020-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20200923_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='newitem',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
        migrations.AddField(
            model_name='newitem',
            name='winner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
