# Generated by Django 3.1.1 on 2020-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20200923_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='auction_item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
